Repository Khan/perseus, pull requests merged in 2025-10, with the labels that each got.

#2928 [Radio] Bugfix - Ensure fade bars match the background color of container
  .changeset/curly-adults-travel.md
  packages/perseus/src/util/colors.test.ts
  packages/perseus/src/util/colors.ts
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice.module.css
Labels: project: new radio widget, olc-5.0.2f60c

#2820 docs(changeset): Remove the isLastUsedWidget property from Perseus, as it is not used.
  .changeset/weak-candles-hammer.md
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/mixins/widget-prop-denylist.ts
  packages/perseus/src/renderer.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx
  packages/perseus/src/widgets/passage/__tests__/passage.test.tsx
  packages/perseus/src/widgets/radio/__stories__/base-radio.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/base-radio.test.tsx
  packages/perseus/src/widgets/radio/base-radio.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
Labels: olc-5.0.11e3f

#2945 [Radio] Bugfix - Borders next to correct choices should not show
  .changeset/shy-cats-cheat.md
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-initial-state-regression.stories.tsx
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-interactions-regression.stories.tsx
  packages/perseus/src/widgets/radio/choice.module.css
Labels: project: new radio widget, olc-5.0.853e0

#2936 Test that the ItemDiff component will render an image diff
  .changeset/fifty-buttons-join.md
  packages/perseus-editor/src/__tests__/editor.test.tsx
  packages/perseus-editor/src/diffs/__tests__/item-diff.test.tsx
  packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/components/__tests__/svg-image.test.tsx
  packages/perseus/src/widgets/image/image.test.ts
  testing/image-loader-utils.ts
Labels: olc-5.0.853e0

#2942 Definition style update based on Figma designs
  .changeset/lovely-pants-add.md
  packages/perseus/src/widgets/definition/definition.tsx
Labels: project agnostic, olc-5.0.853e0

#2949 Return preferred popover direction to editor and fix bug
  .changeset/nasty-readers-mix.md
  packages/perseus-editor/src/all-editors.ts
  packages/perseus-editor/src/widgets/__docs__/label-image-editor.stories.tsx
  packages/perseus-editor/src/widgets/__tests__/__snapshots__/label-image-editor.test.tsx.snap
  packages/perseus-editor/src/widgets/__tests__/label-image-editor.test.tsx
  packages/perseus-editor/src/widgets/label-image-editor/__docs__/answer-choices.stories.tsx
  packages/perseus-editor/src/widgets/label-image-editor/__docs__/behavior.stories.tsx
  packages/perseus-editor/src/widgets/label-image-editor/__docs__/marker.stories.tsx
  packages/perseus-editor/src/widgets/label-image-editor/__docs__/question-markers.stories.tsx
  packages/perseus-editor/src/widgets/label-image-editor/__docs__/select-image.stories.tsx
  packages/perseus-editor/src/widgets/label-image-editor/answer-choices.tsx
  packages/perseus-editor/src/widgets/label-image-editor/behavior.test.tsx
  packages/perseus-editor/src/widgets/label-image-editor/behavior.tsx
  packages/perseus-editor/src/widgets/label-image-editor/label-image-editor.module.css
  packages/perseus-editor/src/widgets/label-image-editor/label-image-editor.tsx
  packages/perseus-editor/src/widgets/label-image-editor/marker.tsx
  packages/perseus-editor/src/widgets/label-image-editor/question-markers.tsx
  packages/perseus-editor/src/widgets/label-image-editor/select-image.tsx
  packages/perseus-editor/src/widgets/label-image/__stories__/behavior.stories.tsx
Labels: project agnostic, olc-5.0.8d91b

#2950 [Radio] Bugfix - Selected choices don't turn blue when in articles
  .changeset/violet-files-accept.md
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-interactions-regression.stories.tsx
  packages/perseus/src/widgets/radio/choice.module.css
Labels: olc-5.0.8d91b
