Repository Khan/perseus, pull requests merged in 2025-08, with the labels that each got.

#2755 `choicesSelected` bug in `getPromptJSON`
  .changeset/five-pans-exist.md
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
Labels: olc-5.0.6d36a

#2756 Change some text in README to trigger Version Packages
  .changeset/modern-cobras-bake.md
  packages/perseus/README.md
Labels: olc-5.0.4a131

#2758 Categorizer UserInput parsing issue (null / undefined values)
  .changeset/weak-dots-wave.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.ts
  packages/perseus-core/src/validation.types.ts
  packages/perseus/src/widget-ai-utils/categorizer/categorizer-ai-utils.ts
  packages/perseus/src/widgets/categorizer/categorizer.tsx
Labels: olc-5.0.4a131

#2761 Sync Dependencies
  .changeset/thirty-tigers-greet.md
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: project agnostic, olc-5.0.4a131

#2763 Wrap StoryBook preview in UserInputManager
  .changeset/tame-gorillas-cry.md
  packages/perseus-editor/src/__docs__/editor-page-with-storybook-preview.tsx
  packages/perseus-editor/src/content-preview.tsx
  packages/perseus/src/index.ts
Labels: project agnostic, olc-5.0.4a131

#2765 Update snapshots
  .changeset/afraid-pandas-deny.md
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
Labels: olc-5.0.e3fd9

#2766 Update snapshots again
  .changeset/serious-carpets-design.md
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
Labels: olc-5.0.b27e5

#2767 Add Perseus logo in Storybook
  .changeset/empty-plums-love.md
  .storybook/manager.ts
  .storybook/theme.ts
  static/perseus-logo.svg
Labels: olc-5.0.e3fd9

#2745 [Radio] Refactor multiple choice component (logic and UI updates)
  .changeset/thick-camels-fry.md
  jest-css-modules-transform-config.js
  packages/perseus/src/perseus-api.tsx
  packages/perseus/src/styles/widgets/radio.css
  packages/perseus/src/widgets/radio/__stories__/multiple-choice-option.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/__snapshots__/multiple-choice.test.ts.snap
  packages/perseus/src/widgets/radio/__tests__/choice-indicator.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice-component.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice-option.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice.test.ts
  packages/perseus/src/widgets/radio/choice-indicator.module.css
  packages/perseus/src/widgets/radio/choice-indicator.new.tsx
  packages/perseus/src/widgets/radio/choice-none-above.new.tsx
  packages/perseus/src/widgets/radio/choice.module.css
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/focus-ring.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-option.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice.module.css
  packages/perseus/src/widgets/radio/option-status.new.tsx
  packages/perseus/src/widgets/radio/radio-test.module.css
Labels: project: new radio widget, olc-5.0.d08c8

#2772 Fix storybook theme, change use of WB colors
  .changeset/wet-icons-switch.md
  .storybook/theme.ts
Labels: olc-5.0.b27e5

#2771 [Interactive Graph] | (CX) | Use dynamically resizing textarea for Description field
  .changeset/healthy-carpets-draw.md
  packages/perseus-editor/src/components/auto-resizing-text-area.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-description.tsx
  packages/perseus-editor/src/widgets/radio/radio-option-settings.tsx
Labels: olc-5.0.b27e5

#2762 feat(LEMS-3070): Add IDs to radio choices
  .changeset/ten-adults-count.md
  config/test/crypto-polyfill.js
  config/test/test.config.js
  packages/perseus-core/src/accessibility.test.ts
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/array.test.ts
  packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/array.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.mockData.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-core/src/traversal.test.ts
  packages/perseus-core/src/utils/item-has-rationales.test.ts
  packages/perseus-core/src/utils/split-perseus-item.test.ts
  packages/perseus-core/src/utils/split-perseus-renderer.test.ts
  packages/perseus-core/src/widgets/radio/derive-num-correct.test.ts
  packages/perseus-core/src/widgets/radio/derive-num-correct.ts
  packages/perseus-core/src/widgets/radio/radio-util.test.ts
  packages/perseus-core/src/widgets/radio/radio-util.ts
  packages/perseus-editor/package.json
  packages/perseus-editor/src/widgets/__tests__/radio-editor.mockData.ts
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  packages/perseus-editor/src/widgets/radio/utils.test.ts
  packages/perseus-score/src/had-empty-diner-widgets.test.ts
  packages/perseus-score/src/widgets/group/score-group.test.ts
  packages/perseus-score/src/widgets/radio/score-radio.test.ts
  packages/perseus/src/__testdata__/extract-perseus-data.testdata.ts
  packages/perseus/src/__testdata__/renderer.testdata.ts
  packages/perseus/src/__testdata__/server-item-renderer.testdata.ts
  packages/perseus/src/__tests__/extract-perseus-data.test.ts
  packages/perseus/src/user-input-manager.test.tsx
  packages/perseus/src/util/extract-perseus-data.test.ts
  packages/perseus/src/widget-ai-utils/group/group-ai-utils.testdata.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts
  packages/perseus/src/widgets/graded-group-set/graded-group-set.testdata.ts
  packages/perseus/src/widgets/graded-group/graded-group.testdata.ts
  packages/perseus/src/widgets/group/group.test.tsx
  packages/perseus/src/widgets/group/group.testdata.ts
  packages/perseus/src/widgets/radio/__tests__/answerless-radio.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice.test.ts
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
  packages/perseus/src/widgets/radio/radio-question-builder.test.ts
  packages/perseus/src/widgets/radio/radio-question-builder.ts
  packages/perseus/src/widgets/radio/serialize-radio.test.ts
Labels: project: new radio widget, schema-change, item-splitting-change, olc-5.0.4a131

#2778 Perseus documentation improvements
  .changeset/thirty-candles-taste.md
  .storybook/global.css
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/preview.tsx
  static/perseus-favicon.svg
  static/storybook-styles/preview.css
Labels: olc-5.0.b27e5

#2782 Update codeowners for new radio widget project
  .changeset/modern-moons-attend.md
  .github/CODEOWNERS
Labels: project: new radio widget, olc-5.0.b27e5

#2780 feat(LEMS-3069): Consumes choice Ids in radio widget
  .changeset/wild-hotels-help.md
  packages/perseus/src/widgets/radio/__tests__/base-radio.testdata.ts
  packages/perseus/src/widgets/radio/base-radio.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
Labels: project: new radio widget, olc-5.0.b27e5

#2785 random change to trigger version packages workflows
  .changeset/gorgeous-deers-poke.md
  packages/perseus-core/src/widgets/radio/radio-util.ts
Labels: olc-5.0.b27e5

#2792 Remove Expression transform
  .changeset/lovely-tomatoes-speak.md
  packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx
  packages/perseus/src/widgets/expression/expression.test.tsx
  packages/perseus/src/widgets/expression/expression.tsx
Labels: olc-5.0.11e3f

#2793 Remove transform from InputNumber
  .changeset/tall-clouds-report.md
  packages/perseus/src/widgets/input-number/input-number.test.ts
  packages/perseus/src/widgets/input-number/input-number.tsx
Labels: olc-5.0.11e3f

#2787 Remove forced bold from Free Response question
  .changeset/olive-news-report.md
  packages/perseus/src/styles/widgets/free-response.css
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/free-response/free-response.stories.tsx
  packages/perseus/src/widgets/free-response/free-response.tsx
Labels: olc-5.0.b27e5

#2797 Remove NumericInput transform
  .changeset/lovely-vans-sneeze.md
  packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.test.ts
  packages/perseus/src/widgets/numeric-input/utils.test.ts
  packages/perseus/src/widgets/numeric-input/utils.ts
Labels: olc-5.0.11e3f

#2804 Adjust Storybook styling to not interfere with widget styles
  .changeset/lemon-avocados-report.md
  static/storybook-styles/preview.css
Labels: olc-5.0.11e3f

#2788 Fix strong styling issue not properly applying to rendered text
  .changeset/olive-flies-play.md
  .storybook/global.css
  .storybook/preview.tsx
  .storybook/styles/base-element-styles.css
  .storybook/styles/base-page-styles.css
  .storybook/styles/classic.css
  .storybook/styles/reset.css
  .storybook/styles/shared.css
  .storybook/styles/thunderblocks.css
Labels: olc-5.0.b27e5

#2806 [Radio] Use choice IDs for the choice keys in the editor
  .changeset/new-bugs-burn.md
  packages/perseus-editor/src/widgets/radio/editor.tsx
Labels: olc-5.0.11e3f

#2803 [Radio] Enhance content for screen reader access
  .changeset/five-wasps-drum.md
  packages/perseus/src/widgets/radio/__stories__/choice-indicator.stories.tsx
  packages/perseus/src/widgets/radio/__stories__/multiple-choice-option.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/choice-indicator.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice-component.test.tsx
  packages/perseus/src/widgets/radio/__tests__/multiple-choice-option.test.tsx
  packages/perseus/src/widgets/radio/choice-indicator.new.tsx
  packages/perseus/src/widgets/radio/choice.module.css
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice.module.css
Labels: project: new radio widget, olc-5.0.b27e5

#2811 [Radio] Add comments explaining accessibility coding, add attributes to aid in accessibility
  .changeset/popular-lobsters-sell.md
  packages/perseus/src/widgets/radio/__docs__/a11y.mdx
  packages/perseus/src/widgets/radio/__tests__/choice-indicator.test.tsx
  packages/perseus/src/widgets/radio/choice-indicator.new.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
Labels: project: new radio widget, olc-5.0.11e3f

#2810 [Image] (UX) Remove the custom mobile styling for title and caption
  .changeset/heavy-beers-carry.md
  packages/perseus/src/styles/styles.css
  packages/perseus/src/widgets/image/__snapshots__/image.test.ts.snap
  packages/perseus/src/widgets/image/image.tsx
Labels: olc-5.0.11e3f

#2815 [Radio] Adjust the transition time of the indicator so that it doesn't appear out of sync with the "Check" button
  .changeset/odd-plums-juggle.md
  packages/perseus/src/widgets/radio/choice-indicator.module.css
Labels: olc-5.0.11e3f

#2827 [Image] Add codeowners for the image widget project
  .changeset/nine-houses-explode.md
  .github/CODEOWNERS
Labels: olc-5.0.e7698

#2819 [Image] | (DX) | Add regression stories for Image widget
  .changeset/empty-steaks-tell.md
  packages/perseus/src/widgets/image/__docs__/image-regression.stories.tsx
Labels: olc-5.0.11e3f

#2822 [Radio] Fix missing styling when showing solution in graded group
  .changeset/lucky-badgers-share.md
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-demo.new.stories.tsx
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-interaction-regression.stories.tsx
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-static-regression.stories.tsx
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
Labels: olc-5.0.11e3f

#2826 [Radio] Fix how Graphie text is placed when inside a choice
  .changeset/cuddly-owls-pay.md
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-demo.new.stories.tsx
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-static-regression.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
  packages/perseus/src/widgets/radio/choice.module.css
Labels: olc-5.0.11e3f

#2824 [Image] | (DX) | Modernize the Image widget code
  .changeset/smooth-ties-lay.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus/src/widget-ai-utils/image/image-ai-utils.ts
  packages/perseus/src/widgets/image/image.class.tsx
  packages/perseus/src/widgets/image/image.tsx
  packages/perseus/src/widgets/image/index.ts
Labels: schema-change, olc-5.0.11e3f

#2835 Replace WB surface and foreground/border inverse semantic color token usage
  .changeset/wild-coats-pay.md
  packages/perseus-editor/src/widgets/radio/radio-editor.module.css
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  packages/perseus/src/widgets/radio/choice-indicator.module.css
  packages/perseus/src/widgets/radio/multiple-choice.module.css
  packages/perseus/src/widgets/video/__snapshots__/video.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
  testing/debug-accordion-ui.module.css
  utils/extract-css.js
Labels: olc-5.0.e7698

#2837 [Radio] Bugfix - Choice text not changing color when selected
  .changeset/thick-dogs-double.md
  packages/perseus/src/widgets/radio/__docs__/multiple-choice-interaction-regression.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
  packages/perseus/src/widgets/radio/choice.module.css
Labels: olc-5.0.e7698

#2838 [Radio] Bugfix - Correctness indicator was missing in static widget
  .changeset/gorgeous-eyes-cheat.md
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
Labels: olc-5.0.e7698

#2831 [Radio] Fix to allow users to scroll content after multiple choice is checked
  .changeset/strong-candles-argue.md
  packages/perseus/src/components/scrollable-view.test.tsx
  packages/perseus/src/components/scrollable-view.tsx
  packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
Labels: project: new radio widget, olc-5.0.e7698

#2834 [functionally-equivalent] Updating (New) Radio widget to be fully functional.
  .changeset/silent-hairs-exercise.md
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
Labels: olc-5.0.11e3f

#2836 Add documentation warning for using Graphie component
  .changeset/dirty-cougars-marry.md
  packages/perseus/src/components/__docs__/graphie.mdx
  packages/perseus/src/components/__docs__/graphie.stories.tsx
  types/assets.d.ts
Labels: olc-5.0.e7698

#2798 Remove NumberLine transforms
  .changeset/polite-guests-lay.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/number-line-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widgets-map.test.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus/src/__tests__/extract-perseus-data.test.ts
  packages/perseus/src/user-input-manager.test.tsx
  packages/perseus/src/widget-ai-utils/number-line/number-line-ai-utils.test.ts
  packages/perseus/src/widgets/number-line/number-line.test.ts
  packages/perseus/src/widgets/number-line/number-line.testdata.ts
  packages/perseus/src/widgets/number-line/number-line.tsx
  packages/perseus/src/widgets/number-line/serialize-number-line.test.ts
Labels: schema-change, item-splitting-change, olc-5.0.11e3f

#2842 [Image] | (CX) | Modernize the Image widget editor UI
  .changeset/eight-trees-travel.md
  packages/perseus-editor/src/__tests__/editor.test.tsx
  packages/perseus-editor/src/widgets/__docs__/image-editor.stories.tsx
  packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx
  packages/perseus-editor/src/widgets/image-editor/image-editor.module.css
  packages/perseus-editor/src/widgets/image-editor/image-editor.tsx
  packages/perseus-editor/src/widgets/image-editor/image-settings.tsx
  packages/perseus-editor/src/widgets/image-editor/image-url-input.tsx
Labels: olc-5.0.e7698

#2849 Sync dev deps with frontend
  .changeset/cold-balloons-protect.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.e7698

#2852 [Image] | (DX) | Revert to old way of saving empty string data for the sake of data consistency
  .changeset/fast-ways-buy.md
  packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx
  packages/perseus-editor/src/widgets/image-editor/image-settings.tsx
  packages/perseus-editor/src/widgets/image-editor/image-url-input.tsx
Labels: olc-5.0.e7698
