Repository Khan/perseus, pull requests merged in 2025-05, with the labels that each got.

#2421 Allow widgets in hints to open/close with the Editor toggle
  .changeset/early-planets-try.md
  packages/perseus-editor/src/editor-page.tsx
  packages/perseus-editor/src/hint-editor.tsx
Labels: olc-5.0.407da

#2426 Answerless InputNumber
  .changeset/chilly-days-push.md
  packages/perseus-core/src/widgets/input-number/index.ts
  packages/perseus-core/src/widgets/input-number/input-number-util.test.ts
  packages/perseus-core/src/widgets/input-number/input-number-util.ts
  packages/perseus-core/src/widgets/logic-export.types.ts
  packages/perseus/src/widgets/input-number/input-number.stories.tsx
  packages/perseus/src/widgets/input-number/input-number.test.ts
  packages/perseus/src/widgets/input-number/input-number.tsx
Labels: olc-5.0.407da

#2451 Remove immutable-data rule for tests and stories
  .changeset/silver-lions-lick.md
  .eslintrc.js
Labels: project agnostic, olc-5.0.65aec

#2448 [TUT-1590] Add itemHasHints & itemHasRationales utilities
  .changeset/soft-years-brush.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/utils/item-has-hints.test.ts
  packages/perseus-core/src/utils/item-has-hints.ts
  packages/perseus-core/src/utils/item-has-rationales.test.ts
  packages/perseus-core/src/utils/item-has-rationales.ts
Labels: olc-5.0.65aec

#2449 Expression Editor: UI update to clarify how things work
  .changeset/new-tips-provide.md
  .changeset/pretty-buses-listen.md
  packages/perseus-editor/src/widgets/expression-editor.tsx
  packages/perseus/src/components/button-group.tsx
  packages/perseus/src/widgets/grapher/__snapshots__/grapher.test.ts.snap
Labels: olc-5.0.a8bef

#2447 Minor test cleanup
  .changeset/chilly-stingrays-poke.md
  packages/perseus/src/__tests__/server-item-renderer.test.tsx
Labels: project agnostic, olc-5.0.65aec

#2452 Use interface for shared ref type
  .changeset/good-trains-dream.md
  packages/perseus/src/components/simple-keypad-input.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.tsx
Labels: olc-5.0.f25a3

#2460 [🔥AUDIT🔥] Fix Storybook base font size
  .changeset/yellow-taxis-own.md
  .storybook/main.ts
Labels: audit, olc-5.0.65aec

#2454 Answerless iFrame
  .changeset/thin-pumpkins-jump.md
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/iframe/iframe.test.ts
  packages/perseus/src/widgets/iframe/iframe.tsx
Labels: olc-5.0.65aec

#2458 Answerless Grapher
  .changeset/real-coats-march.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/widgets/grapher/grapher-util.ts
  packages/perseus/src/widgets/grapher/grapher.cypress.ts
  packages/perseus/src/widgets/grapher/grapher.stories.tsx
  packages/perseus/src/widgets/grapher/grapher.testdata.ts
  packages/perseus/src/widgets/grapher/grapher.tsx
Labels: 🐍 project: sss, olc-5.0.65aec

#2466 Update bump command with new flags
  .changeset/great-pens-talk.md
  .github/workflows/node-ci.yml
Labels: project agnostic, olc-5.0.65aec

#2444 Ensure Orderer Editor updates Options property in change callback
  .changeset/fluffy-onions-camp.md
  packages/perseus-editor/src/editor-page.test.tsx
  packages/perseus-editor/src/widgets/__tests__/orderer-editor.test.tsx
  packages/perseus-editor/src/widgets/orderer-editor.tsx
Labels: olc-5.0.65aec

#2465 Grapher: add type check, fix possible bug
  .changeset/yellow-countries-drive.md
  packages/perseus/src/widgets/grapher/grapher.tsx
Labels: olc-5.0.65aec

#2420 Functional component update, removal of focus event from new radio
  .changeset/sixty-jokes-vanish.md
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/radio-component.new.tsx
  packages/perseus/src/widgets/radio/radio.class.new.tsx
  packages/perseus/src/widgets/radio/radio.ff.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
Labels: olc-5.0.fb2b9, project: new radio widget

#2478 docs(changeset): Ensure new radio project files are properly linked to the new files.
  .changeset/late-ghosts-jam.md
  packages/perseus/src/widgets/radio/choice-none-above.new.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
Labels: project: new radio widget, olc-5.0.f1826

#2477 Use ContentPreview for storybook EditorPage preview
  .changeset/wicked-clocks-march.md
  packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx
  packages/perseus-editor/src/content-preview.tsx
Labels: olc-5.0.4b96c

#2456 Remove pre-install check which warns if you aren't using pnpm - super slow!
  .changeset/four-walls-remember.md
  package.json
Labels: olc-5.0.f25a3

#2463 Edit area cleanup
  .changeset/odd-ladybugs-remain.md
  packages/perseus-editor/src/editor-page.tsx
  packages/perseus-editor/src/item-editor.tsx
Labels: olc-5.0.f25a3

#2486 Update Free Response styles and accessibility
  .changeset/spicy-seas-mix.md
  packages/perseus/package.json
  packages/perseus/src/styles/perseus-renderer.less
  packages/perseus/src/styles/widgets/free-response.css
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/free-response/free-response.stories.tsx
  packages/perseus/src/widgets/free-response/free-response.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.f1826

#2487 Extend parseAndMigratePerseusItem to accept an object as well as string
  .changeset/seven-toys-lay.md
  packages/perseus-core/src/parse-perseus-json/index.ts
  packages/perseus-core/src/parse-perseus-json/parse-perseus-json.test.ts
Labels: olc-5.0.4b96c

#2483 Add registry guard
  .changeset/hip-crabs-vanish.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/utils/registry.test.ts
  packages/perseus-core/src/utils/registry.ts
  packages/perseus-core/src/widgets/core-widget-registry.test.ts
  packages/perseus-core/src/widgets/core-widget-registry.ts
  packages/perseus-core/src/widgets/upgrade.ts
  packages/perseus-score/src/widgets/widget-registry.ts
  packages/perseus/src/__tests__/widgets-pre-registration.test.ts
  packages/perseus/src/__tests__/widgets.test.ts
  packages/perseus/src/widgets.ts
Labels: olc-5.0.37c28

#2440 docs(changeset): New feature for PhET Widget to provide an option for full screen on mobile devices.
  .changeset/friendly-years-share.md
  packages/perseus/src/perseus-api.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/phet-simulation/phet-simulation.stories.tsx
  packages/perseus/src/widgets/phet-simulation/phet-simulation.test.ts
  packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
Labels: olc-5.0.65aec

#2488 Cursor: Add rule to help describe Perseus in general
  .changeset/sharp-mice-rest.md
  .cursor/rules/pereus-overview.mdc
Labels: olc-5.0.4b96c

#2492 [Radio Widget Project] Standardize Functional Component Declarations + Code Organization
  .changeset/fluffy-owls-enjoy.md
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/choice-a11y-text.new.ts
  packages/perseus/src/widgets/radio/choice-none-above.new.tsx
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/focus-ring.new.tsx
  packages/perseus/src/widgets/radio/option-status.new.tsx
  packages/perseus/src/widgets/radio/radio.class.new.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
  packages/perseus/src/widgets/radio/utils/general-utils.test.ts
  packages/perseus/src/widgets/radio/utils/general-utils.ts
  packages/perseus/src/widgets/radio/utils/string-utils.test.ts
  packages/perseus/src/widgets/radio/utils/string-utils.ts
Labels: project: new radio widget, olc-5.0.f1826

#2481 Add Horizontal Scrollbar for New Radio Widget to allow users to visually scroll a long radio option content
  .changeset/serious-pandas-melt.md
  packages/perseus/src/components/scrollable-view.tsx
  packages/perseus/src/strings.ts
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/choice-icon/choice-icon-styles.ts
  packages/perseus/src/widgets/radio/choice-icon/choice-icon.new.tsx
  packages/perseus/src/widgets/radio/choice.new.tsx
  testing/split-view.tsx
Labels: project: new radio widget, olc-5.0.f1826

#2493 Use LabeledField in FreeResponseEditor
  .changeset/swift-lobsters-share.md
  packages/perseus-editor/package.json
  packages/perseus-editor/src/widgets/free-response-editor.tsx
  pnpm-lock.yaml
Labels: olc-5.0.3d2dc

#2474 Adds a warning message in the Issues Panel when a content creator uses a widget marked as inaccessible
  .changeset/old-needles-sit.md
  packages/perseus-core/src/widgets/core-widget-registry.ts
  packages/perseus-core/src/widgets/logic-export.types.ts
  packages/perseus-core/src/widgets/upgrade.ts
  packages/perseus-editor/src/__tests__/issues-panel.test.tsx
  packages/perseus-editor/src/issue-details.tsx
  packages/perseus-editor/src/issues-panel.tsx
  packages/perseus-editor/src/item-editor.tsx
  packages/perseus-editor/src/messages.ts
  packages/perseus-linter/src/index.ts
  packages/perseus-linter/src/proptypes.ts
  packages/perseus-linter/src/rule.ts
  packages/perseus-linter/src/rules/all-rules.ts
  packages/perseus-linter/src/rules/inaccessible-widget.ts
  packages/perseus-linter/src/run-linter.ts
  packages/perseus-linter/src/types.ts
Labels: olc-5.0.f1826

#2502 This is a feature-branch pull-request from `feature/free-response-widget` to `main`
  .changeset/dirty-phones-train.md
  .changeset/four-cougars-work.md
  .changeset/grumpy-lamps-allow.md
  .changeset/healthy-camels-warn.md
  .changeset/kind-eels-burn.md
  .changeset/mean-items-share.md
  .changeset/real-rocks-build.md
  .changeset/spicy-seas-mix.md
  .changeset/swift-lobsters-share.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widgets-map.ts
  packages/perseus-core/src/validation.types.ts
  packages/perseus-core/src/widgets/free-response/free-response-util.test.ts
  packages/perseus-core/src/widgets/free-response/free-response-util.ts
  packages/perseus-core/src/widgets/free-response/index.ts
  packages/perseus-core/src/widgets/logic-export.types.ts
  packages/perseus-editor/package.json
  packages/perseus-editor/src/all-editors.ts
  packages/perseus-editor/src/widgets/__stories__/free-response-editor.stories.tsx
  packages/perseus-editor/src/widgets/__tests__/free-response-editor.test.tsx
  packages/perseus-editor/src/widgets/free-response-editor.tsx
  packages/perseus-score/src/error-codes.ts
  packages/perseus-score/src/widgets/free-response/score-free-response.test.ts
  packages/perseus-score/src/widgets/free-response/score-free-response.ts
  packages/perseus-score/src/widgets/free-response/validate-free-response.test.ts
  packages/perseus-score/src/widgets/free-response/validate-free-response.ts
  packages/perseus-score/src/widgets/widget-registry.ts
  packages/perseus/package.json
  packages/perseus/src/extra-widgets.ts
  packages/perseus/src/strings.ts
  packages/perseus/src/styles/perseus-renderer.less
  packages/perseus/src/styles/widgets/free-response.css
  packages/perseus/src/util/widget-enum-utils.ts
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/free-response/free-response.stories.tsx
  packages/perseus/src/widgets/free-response/free-response.test.tsx
  packages/perseus/src/widgets/free-response/free-response.testdata.ts
  packages/perseus/src/widgets/free-response/free-response.tsx
  packages/perseus/src/widgets/free-response/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.3d2dc, integration-branch, feature-branch

#2494 Add story for radio widget single select with images and scroll
  .changeset/breezy-chefs-roll.md
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
  packages/perseus/src/widgets/radio/choice-icon/choice-icon-styles.ts
  packages/perseus/src/widgets/radio/choice-icon/choice-icon.new.tsx
  packages/perseus/src/widgets/radio/choice-icon/shared-styles.ts
  packages/perseus/src/widgets/radio/choice.new.tsx
Labels: project: new radio widget, olc-5.0.37c28

#2491 Wonder Blocks: Updates WB Button instances to match new API (color -> actionType)
  .changeset/ten-lobsters-lie.md
  packages/perseus-editor/src/widgets/expression-editor.tsx
  packages/perseus-editor/src/widgets/free-response-editor.tsx
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/__tests__/__snapshots__/server-item-renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
  packages/perseus/src/widgets/matrix/__snapshots__/matrix.test.ts.snap
  packages/perseus/src/widgets/numeric-input/__snapshots__/numeric-input.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.3d2dc

#2509 Ensure that our parser can handle empty strings for labelLocation for Interactive Graphs
  .changeset/tricky-parents-hide.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
  packages/perseus-core/src/utils/split-perseus-item.test.ts
  packages/perseus-core/src/utils/split-perseus-renderer.test.ts
  packages/perseus-core/src/widgets/interactive-graph/index.ts
  packages/perseus/src/widgets/interactive-graph.tsx
Labels: olc-5.0.3d2dc

#2510 Add tab navigation to new radio widget
  .changeset/eighty-swans-love.md
  packages/perseus/src/widgets/radio/choice.new.tsx
Labels: project: new radio widget, olc-5.0.3d2dc

#2516 Add typesafe parser for Categorizer's user input type
  .changeset/mean-trains-cover.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.typetest.ts
Labels: olc-5.0.3d2dc

#2495 Update label image widget to handle answerless data and do some cleanup
  .changeset/green-yaks-scream.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/widgets/label-image/label-image-util.ts
  packages/perseus-score/src/widgets/label-image/score-label-image.ts
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/label-image/__stories__/label-image.stories.tsx
  packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts
  packages/perseus/src/widgets/label-image/__tests__/label-image.testdata.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
  packages/perseus/src/widgets/label-image/marker.tsx
Labels: olc-5.0.f1826

#2512 Remove preferred popover direction from Label Image editor
  .changeset/three-goats-lay.md
  packages/perseus-editor/src/widgets/label-image-editor.tsx
  packages/perseus-editor/src/widgets/label-image/__stories__/behavior.stories.tsx
  packages/perseus-editor/src/widgets/label-image/behavior.tsx
Labels: olc-5.0.3d2dc

#2511 Update TypeScript config to align with Khan Academy's minimum supported browser
  .changeset/calm-melons-thank.md
  package.json
  packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
  tsconfig-common.json
Labels: olc-5.0.57876

#2443 chore(LEMS-2995): remove code for cross-out functionality
  .changeset/sharp-poets-protect.md
  packages/perseus/src/perseus-api.tsx
  packages/perseus/src/strings.ts
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/radio/__stories__/choice-icon.stories.tsx
  packages/perseus/src/widgets/radio/__stories__/choice.stories.tsx
  packages/perseus/src/widgets/radio/__stories__/option-status.stories.tsx
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
  packages/perseus/src/widgets/radio/__stories__/radio.stories.tsx
  packages/perseus/src/widgets/radio/__tests__/choice.test.tsx
  packages/perseus/src/widgets/radio/__tests__/option-status.test.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/base-radio.tsx
  packages/perseus/src/widgets/radio/choice-a11y-text.ts
  packages/perseus/src/widgets/radio/choice-icon/choice-icon.new.tsx
  packages/perseus/src/widgets/radio/choice-icon/choice-icon.tsx
  packages/perseus/src/widgets/radio/choice-icon/cross-out-line.tsx
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/choice.tsx
  packages/perseus/src/widgets/radio/option-status.new.tsx
  packages/perseus/src/widgets/radio/option-status.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
  packages/perseus/src/widgets/radio/utils/general-utils.test.ts
  packages/perseus/src/widgets/radio/utils/general-utils.ts
  packages/perseus/src/widgets/radio/utils/string-utils.test.ts
  packages/perseus/src/widgets/radio/utils/string-utils.ts
Labels: project: new radio widget, olc-5.0.65aec

#2515 Validate too-long free response inputs
  .changeset/silly-bobcats-sing.md
  packages/perseus-score/src/error-codes.ts
  packages/perseus-score/src/widgets/free-response/validate-free-response.test.ts
  packages/perseus-score/src/widgets/free-response/validate-free-response.ts
  packages/perseus/src/strings.ts
Labels: olc-5.0.3d2dc

#2532 Add isItemAccessible function and enhance types
  .changeset/light-pandas-happen.md
  packages/perseus-core/src/accessibility.test.ts
  packages/perseus-core/src/accessibility.ts
  packages/perseus-core/src/index.ts
Labels: olc-5.0.57876

#2531 Fix getSaveWarnings in Free Response widget
  .changeset/dirty-singers-arrive.md
  packages/perseus-editor/src/widgets/free-response-editor.tsx
  packages/perseus/src/widgets/free-response/free-response.tsx
Labels: olc-5.0.9bb25

#2523 Add typesafe parser for Plotter's user input type
  .changeset/lovely-baboons-shave.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/plotter-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/plotter-user-input.typetest.ts
Labels: 🐍 project: sss, olc-5.0.3d2dc

#2521 Add typesafe parser for Number-line's user input type
  .changeset/popular-suits-ring.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/number-line-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/number-line-user-input.typetest.ts
Labels: 🐍 project: sss, olc-5.0.3d2dc

#2537 Add typesafe parser for Input-number's user input type
  .changeset/sixty-impalas-warn.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/input-number-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/input-number-user-input.typetest.ts
Labels: 🐍 project: sss, olc-5.0.8b3fb

#2538 Add typesafe parser for Label-image's user input type
  .changeset/calm-knives-behave.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/label-image-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/label-image-user-input.typetest.ts
Labels: 🐍 project: sss, olc-5.0.8b3fb

#2527 Support RTL in new radio widget
  .changeset/five-papayas-happen.md
  packages/perseus/src/components/scrollable-view.test.tsx
  packages/perseus/src/components/scrollable-view.tsx
  packages/perseus/src/strings.ts
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/option-status.new.tsx
Labels: project: new radio widget, olc-5.0.3d2dc
