Repository Khan/perseus, pull requests merged in 2025-07, with the labels that each got.

#2630 docs(changeset): Fixed bugs related to numCorrect not updating properly for the Radio widget
  .changeset/tender-masks-tell.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-core/src/widgets/radio/derive-num-correct.test.ts
  packages/perseus-core/src/widgets/radio/derive-num-correct.ts
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
Labels: olc-5.0.0171b

#2574 Ensure that we properly parse any decimals in the userInput's according to the user's locale
  .changeset/sharp-timers-notice.md
  packages/perseus-score/src/util/answer-types.ts
  packages/perseus-score/src/widgets/input-number/score-input-number.test.ts
  packages/perseus-score/src/widgets/input-number/score-input-number.ts
  packages/perseus-score/src/widgets/numeric-input/score-numeric-input.test.ts
  packages/perseus-score/src/widgets/numeric-input/score-numeric-input.ts
Labels: olc-5.0.23186

#2650 [Interactive Graph] [Locked Figures] Add `weight` option to locked line and locked line settings
  .changeset/green-mangos-occur.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/interactive-graph-locked-figures-missing-weights.json
  packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/interactive-graph-locked-polygon-missing-weight.json
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
  packages/perseus/src/widgets/interactive-graphs/graphs/components/arrowhead.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/components/vector.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-line.tsx
  packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-polygon.tsx
Labels: olc-5.0.7fd07

#2668 [Interactive Graph] [Locked Figures] Add `weight` option to locked vector and locked vector settings
  .changeset/itchy-news-wait.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-vector.tsx
Labels: olc-5.0.d08c8

#2669 [Interactive Graph] [Locked Figures] Add weight option to locked ellipse and locked ellipse settings
  .changeset/strange-sloths-prove.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-ellipse.tsx
Labels: olc-5.0.d08c8

#2683 Perseus 65.6.0 Sync dependencies before release
  .changeset/happy-shrimps-attack.md
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/__tests__/__snapshots__/server-item-renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
  packages/perseus/src/widgets/matrix/__snapshots__/matrix.test.ts.snap
  packages/perseus/src/widgets/numeric-input/__snapshots__/numeric-input.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.d08c8

#2681 [Interactive Graph] [Polygon] Fix concave polygon vertex labels jumping between interior and exterior angles
  .changeset/tiny-apes-love.md
  packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.test.ts
  packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/polygon.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
Labels: olc-5.0.d08c8

#2691 Remove getDOMNodeForPath from PythonProgram
  .changeset/breezy-insects-shop.md
  packages/perseus/src/widgets/python-program/python-program.tsx
Labels: project agnostic, olc-5.0.d08c8

#2689 Mark `deprecated-standin` widget as accessible
  .changeset/loud-cups-ring.md
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-core/src/widgets/core-widget-registry.ts
  packages/perseus-core/src/widgets/deprecated-standin/index.ts
Labels: olc-5.0.0567b

#2693 Delete the blocked-widget and blockquoted-math content linter rules
  .changeset/famous-mice-collect.md
  packages/perseus-linter/src/rules/all-rules.ts
  packages/perseus-linter/src/rules/blockquoted-math.test.ts
  packages/perseus-linter/src/rules/blockquoted-math.ts
  packages/perseus-linter/src/rules/blockquoted-widget.test.ts
  packages/perseus-linter/src/rules/blockquoted-widget.ts
Labels: olc-5.0.d08c8

#2692 [PEICH] Adding check to whether perseus markdown is accessible.
  .changeset/twelve-plants-doubt.md
  packages/perseus-core/.eslintrc.js
  packages/perseus-core/package.json
  packages/perseus-core/src/accessibility.test.ts
  packages/perseus-core/src/accessibility.ts
  packages/perseus-core/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.d08c8

#2694 [PEICH] Fix isAccessible() check to ignore unused widgets
  .changeset/great-crabs-happen.md
  .changeset/hot-turkeys-repair.md
  .changeset/large-moose-burn.md
  packages/perseus-core/.eslintrc.js
  packages/perseus-core/package.json
  packages/perseus-core/src/accessibility.test.ts
  packages/perseus-core/src/accessibility.ts
  packages/perseus-core/tsconfig-build.json
  packages/perseus/src/perseus-markdown.tsx
  packages/pure-markdown/src/__snapshots__/index.test.ts.snap
  packages/pure-markdown/src/index.test.ts
  packages/pure-markdown/src/index.ts
  packages/pure-markdown/src/traversal.test.ts
  packages/pure-markdown/src/traversal.ts
  pnpm-lock.yaml
Labels: olc-5.0.abb57

#2703 Update PR bump documentation
  .changeset/thick-planets-joke.md
  .github/workflows/node-ci.yml
Labels: project agnostic, olc-5.0.d08c8

#2715 [Analytics] Removing deprecated analytics event PerseusInteractiveGraphWidgetRendered
  .changeset/warm-sheep-join.md
  packages/perseus-core/src/analytics.ts
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Labels: olc-5.0.d08c8

#2710 [Interactive Graph] Stop alongEdge labels from overflowing out of graph container
  .changeset/pink-rats-matter.md
  packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx
  packages/perseus/src/widgets/interactive-graphs/backgrounds/utils.ts
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Labels: olc-5.0.d08c8

#2714 [Interactive Graph][Point] Allow points on Point graphs to sit on edge of graph
  .changeset/strange-snakes-lay.md
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts
  packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
  packages/perseus/src/widgets/interactive-graphs/utils.ts
Labels: olc-5.0.d08c8

#2711 Detect schema in Github Action
  .changeset/mean-tips-dream.md
  .editorconfig
  .github/workflows/node-ci.yml
  packages/perseus-core/src/error/errors.ts
Labels: olc-5.0.abb57

#2626 [Radio] | (CX) | Redesign Radio editor UI
  .changeset/nasty-turtles-enjoy.md
  packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx
  packages/perseus-editor/src/__stories__/radio-editor.stories.tsx
  packages/perseus-editor/src/components/perseus-editor-accordion.tsx
  packages/perseus-editor/src/widgets/__stories__/radio-editor.stories.tsx
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  packages/perseus-editor/src/widgets/radio/radio-editor.module.css
  packages/perseus-editor/src/widgets/radio/radio-option-settings.tsx
  packages/perseus-editor/src/widgets/radio/radio-status-pill.tsx
Labels: olc-5.0.0171b

#2727 [Radio] | (CX) | Stop showing NOTA button if NOTA choice exists in the editor
  .changeset/spotty-needles-divide.md
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
Labels: olc-5.0.6d36a

#2728 docs(changeset): Bugfix to ensure Interactive Graph tooltips display points with the same granularity as the snapStep
  .changeset/clever-melons-sparkle.md
  packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.stories.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
Labels: olc-5.0.6d36a

#2731 Bugfix: fix hints in GradedGroups
  .changeset/long-moose-refuse.md
  packages/perseus-editor/src/hint-editor.tsx
  packages/perseus-editor/src/widgets/__tests__/graded-group-editor.test.tsx
  packages/perseus-editor/src/widgets/graded-group-editor.tsx
  packages/perseus/src/user-input-manager.test.tsx
  packages/perseus/src/user-input-manager.tsx
Labels: olc-5.0.6d36a

#2729 [Radio] | (CX) | Implement choice reordering in the editor
  .changeset/four-crews-sort.md
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  packages/perseus-editor/src/widgets/radio/radio-editor.module.css
  packages/perseus-editor/src/widgets/radio/radio-option-settings-actions.tsx
  packages/perseus-editor/src/widgets/radio/radio-option-settings.tsx
  packages/perseus-editor/src/widgets/radio/utils.test.ts
  packages/perseus-editor/src/widgets/radio/utils.ts
Labels: project: new radio widget, olc-5.0.6d36a

#2730 [Interactive Graph] Show min tick when axis doesn't go through it
  .changeset/old-geese-shop.md
  packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts
  packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx
  packages/perseus/src/widgets/interactive-graphs/backgrounds/utils.ts
Labels: olc-5.0.6d36a

#2733 docs(changeset): Bugfix for regression that causes keypad to no longer work in graded groups.
  .changeset/slimy-sloths-listen.md
  packages/perseus/src/widgets/graded-group/graded-group.tsx
Labels: olc-5.0.6d36a

#2734 [Radio] | (CX) | Add dynamically resizing text areas to Radio editor UI
  .changeset/honest-ghosts-attend.md
  packages/perseus-editor/src/widgets/radio/auto-resizing-text-area.tsx
  packages/perseus-editor/src/widgets/radio/radio-editor.module.css
  packages/perseus-editor/src/widgets/radio/radio-option-settings.tsx
Labels: olc-5.0.6d36a

#2726 Schema change detection - change diff format
  .github/workflows/node-ci.yml
Labels: olc-5.0.9442b

#2706 [Editor] Remove unused frameSource prop from EditorPage component
  .changeset/tasty-jars-invent.md
  packages/perseus-editor/src/__docs__/editor-page-with-storybook-preview.tsx
  packages/perseus-editor/src/editor-page.test.tsx
  packages/perseus-editor/src/editor-page.tsx
  packages/perseus-editor/src/widgets/__docs__/interactive-graph-editor.stories.tsx
Labels: olc-5.0.abb57

#2719 Detect item splitting function changes in Github Action
  .changeset/fair-pumpkins-move.md
  .changeset/rude-schools-collect.md
  .github/actions/branch-compare/action.yml
  .github/workflows/node-ci.yml
  packages/perseus-core/package.json
  packages/perseus-core/src/index.item-splitting.ts
  packages/perseus-score/src/index.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
  packages/perseus/src/widgets/plotter/plotter.tsx
Labels: olc-5.0.abb57, item-splitting-change

#2744 Sync dev deps
  .changeset/wicked-weeks-drive.md
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.6d36a

#2742 [Radio] | (DX) | Add null check in radio.ff.tsx
  .changeset/thick-pots-relax.md
  packages/perseus/src/widgets/radio/radio.ff.tsx
Labels: olc-5.0.6d36a

#2432 More test cleanup
  .changeset/poor-lamps-leave.md
  packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx
  packages/perseus/src/widgets/__testutils__/renderQuestion.tsx
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/graded-group/graded-group.test.ts
  packages/perseus/src/widgets/graded-group/graded-group.testdata.ts
  packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx
  packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
Labels: olc-5.0.a8bef
