Repository Khan/perseus, pull requests merged in 2025-04, with the labels that each got.

#2337 Fix MathInput bottom padding to make it consistent with our styling
  .changeset/khaki-berries-fold.md
  packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx
  packages/perseus/src/components/math-input.tsx
Labels: project agnostic

#2351 [🔥AUDIT🔥] Fix Plotter story: Add plotDimensions to testdata
  .changeset/eight-kiwis-reflect.md
  packages/perseus/src/widgets/plotter/plotter.testdata.ts
Labels: audit

#2334 add no-restricted-imports rule
  .changeset/silly-boats-behave.md
  .eslintrc.js
  packages/kas/.eslintrc.js
  packages/keypad-context/.eslintrc.js
  packages/kmath/.eslintrc.js
  packages/math-input/.eslintrc.js
  packages/perseus-core/.eslintrc.js
  packages/perseus-editor/.eslintrc.js
  packages/perseus-linter/.eslintrc.js
  packages/perseus-score/.eslintrc.js
  packages/perseus-utils/.eslintrc.js
  packages/perseus/.eslintrc.js
  packages/pure-markdown/.eslintrc.js
  packages/simple-markdown/.eslintrc.js
Labels: project agnostic

#2362 Update Interactive Graph Parser for Label Location
  .changeset/unlucky-swans-fetch.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
Labels: olc-4.0.628d3

#2368 Create helper for DINER emptiness
  .changeset/dirty-socks-crash.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-score/src/had-empty-diner-widgets.test.ts
  packages/perseus-score/src/has-empty-diner-widgets.ts
  packages/perseus-score/src/index.ts
  packages/perseus-score/src/widgets/radio/validate-radio.ts
Labels: olc-4.0.628d3

#2369 Update pnpm-lock.yaml
  .changeset/big-bags-jump.md
  pnpm-lock.yaml
Labels: olc-4.0.a6c9f

#2373 Don't export mediaQueries - not used (and shouldn't be) outside of Perseus
  .changeset/new-trains-swim.md
  packages/perseus/src/index.ts
Labels: olc-4.0.79514

#2370 Change team-lems-perseus to eng-perseus in Github Actions
  .changeset/cuddly-rice-behave.md
  .github/workflows/release.yml
Labels: olc-5.0.fb2b9

#2376 Fix parsing of `widgets` field in `PerseusRadioChoice`
  .changeset/calm-avocados-retire.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
Labels: olc-4.0.a6c9f

#2364 Upgrade to pnpm 10.8.0
  .changeset/eighty-cows-jam.md
  package.json
Labels: olc-4.0.79514

#2359 Dependabot: Add the two linter packages into the wonder-stuff group
  .changeset/modern-clouds-shout.md
  .github/dependabot.yml
Labels: olc-4.0.79514

#2363 Update CI message
  .github/workflows/node-ci.yml
Labels: project agnostic, olc-4.0.628d3

#2338 Fix ios mobile number keypad that hides away when pressing any key or tabs
  .changeset/orange-eagles-fail.md
  packages/math-input/src/components/keypad/__tests__/__snapshots__/mobile-keypad.test.tsx.snap
  packages/math-input/src/components/keypad/mobile-keypad-internals.tsx
Labels: project agnostic

#2386 Add flags in APIOption, this will be used for feature flags that can be passed from consuming application.
  .changeset/poor-boats-crash.md
  packages/perseus-core/src/feature-flags.ts
  packages/perseus-core/src/index.ts
  packages/perseus/src/types.ts
Labels: project: new radio widget

#2392 Update APIOptions flags type to make it more explicit to Perseus
  .changeset/fluffy-rockets-smell.md
  packages/perseus-core/src/feature-flags.ts
  packages/perseus/src/types.ts
Labels: project: new radio widget

#2378 Fix radio widget parser types
  .changeset/tidy-balloons-hammer.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.typetest.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
Labels: olc-5.0.fb2b9

#2399 [Radio] Implement feature flag usage to isolate forthcoming project work
  .changeset/hungry-years-explain.md
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/choice-a11y-text.new.ts
  packages/perseus/src/widgets/radio/choice-icon/choice-icon.new.tsx
  packages/perseus/src/widgets/radio/choice-none-above.new.tsx
  packages/perseus/src/widgets/radio/choice.new.tsx
  packages/perseus/src/widgets/radio/focus-ring.new.tsx
  packages/perseus/src/widgets/radio/option-status.new.tsx
  packages/perseus/src/widgets/radio/radio-component.new.tsx
  packages/perseus/src/widgets/radio/radio.ff.tsx
  packages/perseus/src/widgets/radio/radio.ts
Labels: olc-5.0.fb2b9, project: new radio widget

#2400 fix broken Story import
  .changeset/fresh-games-doubt.md
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
Labels: olc-5.0.407da

#2396 Answerless Table
  .changeset/khaki-bikes-care.md
  packages/perseus/src/util.test.ts
  packages/perseus/src/util.ts
  packages/perseus/src/widgets/table/__snapshots__/table.test.tsx.snap
  packages/perseus/src/widgets/table/table.stories.tsx
  packages/perseus/src/widgets/table/table.test.tsx
  packages/perseus/src/widgets/table/table.tsx
  packages/perseus/src/widgets/table/test-util.ts
Labels: olc-5.0.fb2b9

#2382 Remove some unneeded Rubric uses
  .changeset/bright-dodos-dress.md
  packages/perseus/src/widgets/expression/expression.tsx
  packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
  packages/perseus/src/widgets/graded-group/graded-group.tsx
  packages/perseus/src/widgets/grapher/grapher.tsx
  packages/perseus/src/widgets/group/group.tsx
  packages/perseus/src/widgets/input-number/input-number.tsx
  packages/perseus/src/widgets/interactive-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/types.ts
  packages/perseus/src/widgets/matcher/matcher.tsx
  packages/perseus/src/widgets/matrix/matrix.tsx
  packages/perseus/src/widgets/measurer/measurer.tsx
  packages/perseus/src/widgets/mock-widgets/mock-widget.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
  packages/perseus/src/widgets/orderer/orderer.tsx
  packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
  packages/perseus/src/widgets/plotter/plotter.tsx
  packages/perseus/src/widgets/sorter/sorter.tsx
  packages/perseus/src/widgets/table/table.stories.tsx
  packages/perseus/src/widgets/table/table.test.tsx
Labels: olc-5.0.fb2b9

#2401 [SR][Pi ticks] Add a coefficient before pi-based values that start with negative pi
  .changeset/nervous-gifts-relax.md
  packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.test.ts
  packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.ts
Labels: olc-5.0.fb2b9

#2398 Remove readonly types from data-schema.ts
  .changeset/bright-guests-march.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/keypad.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/legacy-button-sets.ts
  packages/perseus-core/src/types.ts
  packages/perseus-core/src/utils/random-util.ts
  packages/perseus-core/src/validation.types.ts
  packages/perseus-core/src/widgets/expression/derive-extra-keys.ts
  packages/perseus-core/src/widgets/matcher/matcher-util.ts
  packages/perseus-editor/src/widgets/interactive-graph-editor/start-coords/start-coords-point.tsx
  packages/perseus-editor/src/widgets/label-image-editor.tsx
  packages/perseus-editor/src/widgets/label-image/marker.tsx
  packages/perseus-editor/src/widgets/label-image/question-markers.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  packages/perseus-score/src/widgets/categorizer/score-categorizer.test.ts
  packages/perseus-score/src/widgets/categorizer/validate-categorizer.test.ts
  packages/perseus-score/src/widgets/interactive-graph/score-interactive-graph.ts
  packages/perseus-score/src/widgets/label-image/score-label-image.test.ts
  packages/perseus-score/src/widgets/label-image/validate-label-image.test.ts
  packages/perseus-score/src/widgets/radio/score-radio.ts
  packages/perseus/src/__testdata__/article-renderer.testdata.ts
  packages/perseus/src/__tests__/article-renderer.test.tsx
  packages/perseus/src/__tests__/extract-perseus-data.test.ts
  packages/perseus/src/__tests__/test-items/mock-widget-1-item.ts
  packages/perseus/src/__tests__/test-items/mock-widget-2-item.ts
  packages/perseus/src/util.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
  packages/perseus/src/widgets/expression/expression.test.tsx
  packages/perseus/src/widgets/expression/expression.tsx
  packages/perseus/src/widgets/graded-group-set/graded-group-set.test.ts
  packages/perseus/src/widgets/interactive-graph.tsx
  packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts
  packages/perseus/src/widgets/number-line/number-line.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.test.ts
  packages/perseus/src/widgets/plotter/plotter.tsx
  packages/perseus/src/widgets/radio/radio-component.new.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/table/table.tsx
Labels: olc-5.0.fb2b9

#2385 Stop bundling _any_ mathquill styles/fonts - let host app do that!
  .changeset/tame-grapes-ring.md
  config/build/rollup.config.js
  package.json
  packages/math-input/.eslintrc.js
  packages/math-input/less/main.less
  packages/math-input/package.json
  packages/perseus/src/styles/perseus-renderer.less
  pnpm-lock.yaml
  vendor/mathquill-v1.0.0.tgz
Labels: olc-5.0.9a72e

#2407 [SR] Prepare strings for translation - Add context to interactive graph strings
  .changeset/friendly-seas-scream.md
  packages/perseus/src/strings.ts
Labels: olc-5.0.fb2b9

#2408 Fix formatting of eslintrc file
  .changeset/hip-news-compete.md
  packages/perseus/.eslintrc.js
Labels: project agnostic, olc-5.0.fb2b9

#2410 Bugfix - Redundant reset.css styling was causing font display issues
  .changeset/long-moles-cross.md
  .storybook/global.less
  .storybook/preview.tsx
  .storybook/reset.css
  packages/perseus/src/styles/global.less
  packages/perseus/src/styles/perseus-renderer.less
  packages/perseus/src/styles/reset.css
Labels: olc-5.0.fb2b9

#2387 Update Matrix to render with answerless data
  .changeset/tricky-experts-hide.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/utils/get-matrix-size.ts
  packages/perseus-core/src/widgets/matrix/matrix-util.ts
  packages/perseus/src/util.ts
  packages/perseus/src/util/test-utils.test.ts
  packages/perseus/src/util/test-utils.ts
  packages/perseus/src/widgets/categorizer/categorizer.test.ts
  packages/perseus/src/widgets/matrix/matrix.stories.tsx
  packages/perseus/src/widgets/matrix/matrix.test.ts
  packages/perseus/src/widgets/matrix/matrix.tsx
Labels: olc-5.0.fb2b9

#2403 Add tests to ensure Perseus JSON parsers are idempotent
  .changeset/silly-crabs-pump.md
  packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/defaulted.test.ts
  packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/defaulted.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/hint.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/legacy-button-sets.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/measurer-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/numeric-input-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/perseus-image-background.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/parse-perseus-json-regression.test.ts
Labels: olc-5.0.fb2b9

#2380 Resolve some TODO comments in the Perseus JSON parsing code
  .changeset/late-lamps-join.md
  packages/perseus-core/src/data-schema.ts
  packages/perseus-core/src/parse-perseus-json/exhaustive-test-tool/index.ts
  packages/perseus-core/src/parse-perseus-json/parse-failure-detail.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/measurer-widget.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widgets-map.test.ts
  packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap
  packages/perseus-core/src/utils/split-perseus-item.test.ts
  packages/perseus-core/src/widgets/interactive-graph/interactive-graph-util.test.ts
  packages/perseus-core/src/widgets/measurer/measurer-upgrade.test.ts
  packages/perseus-editor/src/__stories__/editor.stories.tsx
  packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
  packages/perseus/src/__tests__/extract-perseus-data.test.ts
  packages/perseus/src/util/test-utils.ts
  packages/perseus/src/widgets/interactive-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/graph-locked-labels-layer.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-function.test.tsx
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/utils.ts
Labels: olc-5.0.fb2b9

#2416 Update Radio Widget docs to include rationales in the test data
  .changeset/metal-ties-remain.md
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
Labels: olc-5.0.407da

#2413 Update Wonder Blocks dependencies: Tokens as CSS variables
  .changeset/pretty-spiders-invent.md
  .storybook/preview.tsx
  packages/math-input/src/components/tabbar/item.tsx
  packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap
  packages/perseus/src/__tests__/__snapshots__/server-item-renderer.test.tsx.snap
  packages/perseus/src/widgets/deprecated-standin/__snapshots__/deprecated-standin.test.ts.snap
  packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap
  packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
  packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
  packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
  packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  packages/perseus/src/widgets/matrix/__snapshots__/matrix.test.ts.snap
  packages/perseus/src/widgets/numeric-input/__snapshots__/numeric-input.test.ts.snap
  packages/perseus/src/widgets/video/__snapshots__/video.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.407da

#2414 ESLint config cleanup
  .changeset/gorgeous-owls-agree.md
  .eslintrc.js
  dev/package.json
  package.json
  packages/kas/.eslintrc.js
  packages/keypad-context/.eslintrc.js
  packages/kmath/.eslintrc.js
  packages/math-input/.eslintrc.js
  packages/perseus-core/.eslintrc.js
  packages/perseus-core/package.json
  packages/perseus-editor/.eslintrc.js
  packages/perseus-editor/package.json
  packages/perseus-editor/src/diffs/string-array-diff.ts
  packages/perseus-editor/src/editor.tsx
  packages/perseus-linter/.eslintrc.js
  packages/perseus-score/.eslintrc.js
  packages/perseus-utils/.eslintrc.js
  packages/perseus/.eslintrc.js
  packages/perseus/package.json
  packages/perseus/src/util/graphie.test.ts
  packages/perseus/src/util/graphie.ts
  packages/pure-markdown/.eslintrc.js
  packages/simple-markdown/.eslintrc.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vendor/jsdiff/jsdiff.d.ts
  vendor/jsdiff/package.json
  vendor/raphael/package.json
  vendor/raphael/raphael.d.ts
Labels: olc-5.0.a8bef

#2423 Answerless Plotter
  .changeset/late-pillows-search.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/widgets/plotter/plotter-util.ts
  packages/perseus/src/widgets/plotter/plotter.stories.tsx
  packages/perseus/src/widgets/plotter/plotter.test.tsx
  packages/perseus/src/widgets/plotter/plotter.tsx
Labels: olc-5.0.407da

#2427 Jest test correctness fixes
  .changeset/six-pants-brush.md
  packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx
  packages/perseus/src/__tests__/renderer-api.test.tsx
  packages/perseus/src/components/number-input.tsx
  packages/perseus/src/widgets/graded-group/graded-group.test.ts
  packages/perseus/src/widgets/image/__snapshots__/image.test.ts.snap
  packages/perseus/src/widgets/image/image.test.ts
  packages/perseus/src/widgets/input-number/input-number.test.ts
  packages/perseus/src/widgets/interactive-graphs/graphs/circle.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/polygon.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/ray.test.tsx
  packages/perseus/src/widgets/interactive-graphs/graphs/segment.test.tsx
  packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
Labels: olc-5.0.a8bef
