Repository Khan/perseus, pull requests merged in 2025-06, with the labels that each got.

#2541 Add typesafe parser for Grapher's user input type
  .changeset/heavy-fishes-hammer.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/grapher-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/grapher-user-input.typetest.ts
Labels: 🐍 project: sss, olc-5.0.b3e8b

#2550 Add typesafe parser for CS Program's user input type
  .changeset/metal-cars-draw.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/cs-program-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/cs-program-user-input.typetest.ts
Labels: olc-5.0.54312

#2518 docs(changeset): Updates to Radio Scoring to ensure non-specific multiselect questions are marked correctly.
  .changeset/little-goats-prove.md
  packages/perseus-core/src/validation.types.ts
  packages/perseus-score/src/widgets/radio/score-radio.test.ts
  packages/perseus-score/src/widgets/radio/score-radio.ts
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
Labels: project: new radio widget, olc-5.0.3d2dc

#2545 Add recursive typesafe parser for Group's user input type
  .changeset/warm-penguins-tickle.md
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/group-user-input.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/group-user-input.typetest.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/user-input-map.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/user-input-map.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widget-id-components.test.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widget-id-components.ts
  packages/perseus-core/src/parse-perseus-json/perseus-parsers/widgets-map.ts
Labels: olc-5.0.b3e8b

#2553 Adding partially inaccessible functions to InteractiveGraph and LabelImage.
  .changeset/chilly-jokes-teach.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/utils/util.graphie.test.ts
  packages/perseus-core/src/utils/util.graphie.ts
  packages/perseus-core/src/widgets/interactive-graph/index.ts
  packages/perseus-core/src/widgets/label-image/index.ts
  packages/perseus/src/util.ts
Labels: olc-5.0.006c5

#2557 Add rationales to the getPromptJSON output of Radio widget and Label Image widget
  .changeset/metal-spies-double.md
  packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts
  packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.test.ts
  packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
Labels: olc-5.0.23186

#2576 Remove RTL display in New Radio Widget to unblock Perseus from displaying the stories in RTL
  .changeset/little-toys-share.md
  packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
Labels: project: new radio widget, olc-5.0.e0c03

#2579 Fire onRendered callback at least once
  .changeset/green-coins-applaud.md
  .github/workflows/node-ci.yml
  packages/perseus/src/__tests__/server-item-renderer.test.tsx
  packages/perseus/src/server-item-renderer.tsx
Labels: olc-5.0.a2d71

#2431 Add support for CSS Modules
  .changeset/fast-adults-know.md
  config/build/rollup.config.js
  package.json
  packages/perseus/src/widgets/radio/base-radio.new.tsx
  packages/perseus/src/widgets/radio/radio-test.module.css
  pnpm-lock.yaml
  tsconfig.json
  types/assets.d.ts
  utils/extract-css.js
  vite.config.ts
Labels: olc-5.0.407da

#2597 [Interactive Graph] Update autogen labels to correctly reflect locked line vs segment vs ray
  .changeset/eight-geckos-join.md
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx
Labels: olc-5.0.5673f

#2601 docs(changeset): Add test for protecting against edgecase regressions regarding undefined correct value in Radio Widget.
  .changeset/perfect-elephants-joke.md
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
  packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
Labels: project: new radio widget, olc-5.0.bc0e4

#2540 Remove showRationalesForCurrentlySelectedChoices and replace with showSolutions where appropriate
  .changeset/spotty-planes-design.md
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/renderer.tsx
  packages/perseus/src/server-item-renderer.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/graded-group-set/graded-group-set.stories.tsx
  packages/perseus/src/widgets/graded-group-set/graded-group-set.test.ts
  packages/perseus/src/widgets/graded-group-set/graded-group-set.testdata.ts
  packages/perseus/src/widgets/graded-group/graded-group.stories.tsx
  packages/perseus/src/widgets/graded-group/graded-group.test.ts
  packages/perseus/src/widgets/graded-group/graded-group.testdata.ts
  packages/perseus/src/widgets/graded-group/graded-group.tsx
  packages/perseus/src/widgets/group/group.test.tsx
  packages/perseus/src/widgets/group/group.tsx
  packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/radio/radio.class.new.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
  testing/item-renderer-hooks.tsx
Labels: project: new radio widget, olc-5.0.3d2dc

#2607 Bring out your deps!
  .changeset/itchy-camels-destroy.md
  pnpm-workspace.yaml
Labels: olc-5.0.0171b

#2610 Update Code Owners for Radio Project
  .changeset/nice-teachers-exercise.md
  .github/CODEOWNERS
Labels: olc-5.0.0171b

#2583 Replace custom icons with WB components for consistent styling in Perseus Editor
  .changeset/chatty-cats-pretend.md
  packages/perseus-editor/src/__tests__/editor.test.tsx
  packages/perseus-editor/src/__tests__/issues-panel.test.tsx
  packages/perseus-editor/src/components/widget-editor.tsx
  packages/perseus-editor/src/issues-panel.tsx
  packages/perseus-editor/src/styles/perseus-editor.css
Labels: olc-5.0.5673f

#2599 Linter: Break each rule's tests into their own file!
  .changeset/short-hotels-invite.md
  packages/perseus-linter/src/__tests__/rules.test.ts
  packages/perseus-linter/src/__tests__/test-utils.ts
  packages/perseus-linter/src/rules/absolute-url.test.ts
  packages/perseus-linter/src/rules/blockquoted-math.test.ts
  packages/perseus-linter/src/rules/blockquoted-widget.test.ts
  packages/perseus-linter/src/rules/double-spacing-after-terminal.test.ts
  packages/perseus-linter/src/rules/expression-widget.test.ts
  packages/perseus-linter/src/rules/extra-content-spacing.test.ts
  packages/perseus-linter/src/rules/heading-level-1.test.ts
  packages/perseus-linter/src/rules/heading-level-skip.test.ts
  packages/perseus-linter/src/rules/heading-sentence-case.test.ts
  packages/perseus-linter/src/rules/heading-title-case.test.ts
  packages/perseus-linter/src/rules/image-alt-text.test.ts
  packages/perseus-linter/src/rules/image-in-table.test.ts
  packages/perseus-linter/src/rules/image-spaces-around-urls.test.ts
  packages/perseus-linter/src/rules/image-url-empty.test.ts
  packages/perseus-linter/src/rules/image-widget.test.ts
  packages/perseus-linter/src/rules/link-click-here.test.ts
  packages/perseus-linter/src/rules/long-paragraph.test.ts
  packages/perseus-linter/src/rules/math-adjacent.test.ts
  packages/perseus-linter/src/rules/math-align-extra-break.test.ts
  packages/perseus-linter/src/rules/math-align-linebreaks.test.ts
  packages/perseus-linter/src/rules/math-empty.test.ts
  packages/perseus-linter/src/rules/math-frac.test.ts
  packages/perseus-linter/src/rules/math-nested.test.ts
  packages/perseus-linter/src/rules/math-starts-with-space.test.ts
  packages/perseus-linter/src/rules/math-text-empty.test.ts
  packages/perseus-linter/src/rules/math-without-dollars.test.ts
  packages/perseus-linter/src/rules/nested-lists.test.ts
  packages/perseus-linter/src/rules/static-widget-in-question-stem.test.ts
  packages/perseus-linter/src/rules/table-missing-cells.test.ts
  packages/perseus-linter/src/rules/unbalanced-code-delimiters.test.ts
  packages/perseus-linter/src/rules/unescaped-dollar.test.ts
  packages/perseus-linter/src/rules/widget-in-table.test.ts
Labels: olc-5.0.fbd7d

#2605 [CX] Stop steps from auto-updating when range is changed in Interactive Graph editor
  .changeset/mighty-kangaroos-grow.md
  packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx
Labels: olc-5.0.bc0e4

#2609 [Radio] | (DX) | Create a question builder for the Radio widget
  .changeset/friendly-ties-glow.md
  packages/perseus/src/widgets/radio/radio-question-builder.test.ts
  packages/perseus/src/widgets/radio/radio-question-builder.ts
Labels: olc-5.0.bc0e4

#2614 [Radio] | (CX) | Update the style guide link
  .changeset/four-news-visit.md
  packages/perseus-editor/src/widgets/radio/editor.tsx
Labels: olc-5.0.0171b

#2619 [Radio] | (CX) | Convert editor buttons to use Wonder Blocks equivalents
  .changeset/hungry-planets-stare.md
  packages/perseus-editor/package.json
  packages/perseus-editor/src/components/labeled-switch.tsx
  packages/perseus-editor/src/styles/perseus-editor.css
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx
  packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  pnpm-lock.yaml
Labels: olc-5.0.0171b

#2624 chore: Sync dev deps with frontend
  .changeset/tiny-pots-judge.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.0171b

#2602 Remove dead code in Group
  .changeset/spicy-beers-fix.md
  packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
  packages/perseus/src/widgets/group/group.tsx
Labels: olc-5.0.bc0e4

#2616 Rename "Free Response" to "Free Response (Assessments only)"
  .changeset/shiny-crabs-compare.md
  packages/perseus/src/widgets/free-response/free-response.tsx
Labels: olc-5.0.bc0e4

#2627 Wonder Blocks: Remove deprecated semanticColor.text and semanticColor.border token instances
  .changeset/eighty-kiwis-thank.md
  packages/perseus-editor/src/widgets/free-response-editor.tsx
  packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
  packages/perseus/src/widgets/free-response/free-response.tsx
  utils/extract-css.js
Labels: olc-5.0.0171b

#2566 Renderer: separate user input state from render props state
  .changeset/neat-meals-yawn.md
  packages/perseus-core/src/types.ts
  packages/perseus-core/src/validation.types.ts
  packages/perseus/src/__tests__/article-renderer.test.tsx
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/__tests__/server-item-renderer.test.tsx
  packages/perseus/src/__tests__/test-utils.tsx
  packages/perseus/src/__tests__/widgets.test.ts
  packages/perseus/src/components/sortable.tsx
  packages/perseus/src/hint-renderer.tsx
  packages/perseus/src/hints-renderer.tsx
  packages/perseus/src/mixins/widget-prop-denylist.ts
  packages/perseus/src/renderer.tsx
  packages/perseus/src/server-item-renderer.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widget-type-utils.ts
  packages/perseus/src/widgets.ts
  packages/perseus/src/widgets/categorizer/categorizer.test.ts
  packages/perseus/src/widgets/categorizer/categorizer.tsx
  packages/perseus/src/widgets/definition/definition.tsx
  packages/perseus/src/widgets/dropdown/dropdown.tsx
  packages/perseus/src/widgets/explanation/explanation.tsx
  packages/perseus/src/widgets/expression/expression.stories.tsx
  packages/perseus/src/widgets/expression/expression.tsx
  packages/perseus/src/widgets/free-response/free-response.tsx
  packages/perseus/src/widgets/graded-group/graded-group.tsx
  packages/perseus/src/widgets/grapher/grapher.tsx
  packages/perseus/src/widgets/group/group.tsx
  packages/perseus/src/widgets/input-number/input-number.tsx
  packages/perseus/src/widgets/interaction/interaction.tsx
  packages/perseus/src/widgets/interactive-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/types.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
  packages/perseus/src/widgets/matcher/matcher.tsx
  packages/perseus/src/widgets/matrix/matrix.tsx
  packages/perseus/src/widgets/mock-widgets/mock-widget.tsx
  packages/perseus/src/widgets/number-line/number-line.tsx
  packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
  packages/perseus/src/widgets/orderer/orderer.tsx
  packages/perseus/src/widgets/passage/__tests__/passage.test.tsx
  packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
  packages/perseus/src/widgets/plotter/plotter.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/radio/radio.class.new.tsx
  packages/perseus/src/widgets/radio/radio.ff.tsx
  packages/perseus/src/widgets/radio/radio.new.tsx
  packages/perseus/src/widgets/radio/radio.ts
  packages/perseus/src/widgets/sorter/sorter.tsx
  packages/perseus/src/widgets/table/table.tsx
  testing/test-dependencies.tsx
Labels: olc-5.0.e0c03

#2578 Sorter: renderer user input state
  .changeset/fresh-olives-study.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/widgets/sorter/sorter-util.test.ts
  packages/perseus-core/src/widgets/sorter/sorter-util.ts
  packages/perseus-score/src/widgets/sorter/validate-sorter.ts
  packages/perseus/src/components/__tests__/sorter.test.tsx
  packages/perseus/src/widgets/sorter/serialize-sorter.test.ts
  packages/perseus/src/widgets/sorter/sorter.tsx
Labels: olc-5.0.5673f

#2582 IFrame: renderer user input state
  .changeset/ten-cheetahs-confess.md
  packages/perseus/src/widgets/iframe/iframe.tsx
  packages/perseus/src/widgets/iframe/serialize-iframe.test.ts
Labels: olc-5.0.5673f

#2584 CSProgram: renderer user input state
  .changeset/loud-trains-relate.md
  packages/perseus/src/widgets/cs-program/cs-program.tsx
  packages/perseus/src/widgets/cs-program/serialize-cs-program.test.ts
Labels: olc-5.0.5673f

#2586 MockWidget: renderer user input state
  .changeset/large-swans-bake.md
  packages/perseus/src/widgets/mock-widgets/mock-widget.tsx
Labels: olc-5.0.373be

#2588 Plotter: renderer user input state
  .changeset/early-walls-walk.md
  packages/perseus-editor/src/widgets/plotter-editor.tsx
  packages/perseus/src/widgets/plotter/plotter.stories.tsx
  packages/perseus/src/widgets/plotter/plotter.test.tsx
  packages/perseus/src/widgets/plotter/plotter.testdata.ts
  packages/perseus/src/widgets/plotter/plotter.tsx
  packages/perseus/src/widgets/plotter/serialize-plotter.test.ts
Labels: olc-5.0.373be

#2589 InputNumber: renderer user input state
  .changeset/eighty-rice-buy.md
  packages/perseus/src/widgets/input-number/input-number.tsx
  packages/perseus/src/widgets/input-number/serialize-input-number.test.ts
Labels: olc-5.0.373be

#2592 Orderer: renderer user input state
  .changeset/real-mails-thank.md
  packages/perseus/src/widgets/orderer/orderer.tsx
  packages/perseus/src/widgets/orderer/serialize-orderer.test.ts
Labels: olc-5.0.373be

#2577 LabelImage: renderer user input state
  .changeset/flat-wolves-drop.md
  packages/perseus-core/src/types.ts
  packages/perseus-core/src/validation.types.ts
  packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts
  packages/perseus/src/widgets/label-image/__tests__/serialize-label-image.test.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
Labels: olc-5.0.e0c03

#2644 Clean up some change handler stuff
  .changeset/mighty-buses-taste.md
  packages/perseus-editor/src/editor-page.tsx
  packages/perseus-editor/src/editor.tsx
  packages/perseus-editor/src/hint-editor.tsx
  packages/perseus-editor/src/item-editor.tsx
  packages/perseus-editor/src/widgets/group-editor.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
  packages/perseus-editor/src/widgets/video-editor.tsx
  packages/perseus/src/mixins/changeable.ts
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/explanation/explanation.tsx
  packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
  packages/perseus/src/widgets/graded-group/graded-group.tsx
  packages/perseus/src/widgets/grapher/grapher.tsx
  packages/perseus/src/widgets/group/group.tsx
  packages/perseus/src/widgets/image/image.tsx
  packages/perseus/src/widgets/interaction/interaction.tsx
  packages/perseus/src/widgets/passage-ref-target/passage-ref-target.tsx
  packages/perseus/src/widgets/passage-ref/passage-ref.tsx
  packages/perseus/src/widgets/passage/passage.tsx
  packages/perseus/src/widgets/table/table.tsx
  packages/perseus/src/widgets/video/video.tsx
Labels: olc-5.0.7fd07

#2645 LEMS-3247: NumberLine inequality regression
  .changeset/unlucky-dancers-compare.md
  packages/perseus/src/widgets/number-line/number-line.stories.tsx
  packages/perseus/src/widgets/number-line/number-line.test.ts
  packages/perseus/src/widgets/number-line/number-line.testdata.ts
  packages/perseus/src/widgets/number-line/number-line.tsx
Labels: olc-5.0.7fd07

#2651 Bugfix: Plotter dot graph crashing
  .changeset/lucky-mails-repair.md
  packages/perseus/src/widgets/plotter/plotter.stories.tsx
  packages/perseus/src/widgets/plotter/plotter.test.tsx
  packages/perseus/src/widgets/plotter/plotter.testdata.ts
  packages/perseus/src/widgets/plotter/plotter.tsx
Labels: olc-5.0.7fd07

#2628 Remove long-outdated "star property hack"
  .changeset/swift-jobs-poke.md
  packages/perseus/src/styles/util.css
  packages/perseus/src/styles/widgets/radio.css
Labels: olc-5.0.3a4ea

#2652 Bugfix: static switch not working in editor
  .changeset/smooth-apples-visit.md
  packages/perseus-editor/src/components/widget-editor.tsx
  packages/perseus-editor/src/editor-page.test.tsx
  packages/perseus/src/__tests__/server-item-renderer.test.tsx
  packages/perseus/src/index.ts
  packages/perseus/src/mixins/changeable.ts
  packages/perseus/src/mixins/editor-jsonify.ts
  packages/perseus/src/mixins/widget-prop-denylist.ts
  packages/perseus/src/widgets/categorizer/serialize-categorizer.test.ts
  packages/perseus/src/widgets/dropdown/serialize-dropdown.test.ts
  packages/perseus/src/widgets/expression/serialize-expression.test.ts
  packages/perseus/src/widgets/grapher/serialize-grapher.test.ts
  packages/perseus/src/widgets/group/group.test.tsx
  packages/perseus/src/widgets/input-number/serialize-input-number.test.ts
  packages/perseus/src/widgets/interactive-graphs/serialize-interactive-graph.test.ts
  packages/perseus/src/widgets/label-image/__tests__/serialize-label-image.test.ts
  packages/perseus/src/widgets/matrix/serialize-matrix.test.ts
  packages/perseus/src/widgets/number-line/serialize-number-line.test.ts
  packages/perseus/src/widgets/numeric-input/serialize-numeric-input.test.ts
  packages/perseus/src/widgets/orderer/serialize-orderer.test.ts
  packages/perseus/src/widgets/plotter/serialize-plotter.test.ts
  packages/perseus/src/widgets/sorter/serialize-sorter.test.ts
  packages/perseus/src/widgets/table/serialize-table.test.ts
Labels: olc-5.0.7fd07

#2654 LEMS-3257: Fix IG regression regarding user input
  .changeset/ten-lamps-breathe.md
  packages/perseus/src/widgets/interactive-graph.tsx
Labels: olc-5.0.7fd07

#2580 Add template prop to EditorPage
  .changeset/real-hornets-smile.md
  packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx
  packages/perseus-editor/src/editor-page.tsx
  packages/perseus-editor/src/editor.tsx
  packages/perseus-editor/src/item-editor.tsx
Labels: olc-5.0.5673f

#2613 Convert Aphrodite to CSS Modules in scrollable-view component
  .changeset/short-owls-attack.md
  packages/perseus/src/components/scrollable-view.module.css
  packages/perseus/src/components/scrollable-view.tsx
Labels: olc-5.0.bc0e4
