Repository Khan/perseus, pull requests merged in 2025-09, with the labels that each got.

#2854 adds choice ids as part of options for KM
  .changeset/spotty-books-pay.md
  packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
Labels: olc-5.0.5f719

#2857 Remove Radio transforms (take 2)
  .changeset/purple-taxis-itch.md
  packages/perseus-core/src/index.ts
  packages/perseus-core/src/utils/random-util.ts
  packages/perseus/src/__testdata__/renderer.testdata.ts
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/__tests__/widgets.test.ts
  packages/perseus/src/mixins/widget-prop-denylist.ts
  packages/perseus/src/renderer.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts
  packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx
  packages/perseus/src/widgets/group/group.test.tsx
  packages/perseus/src/widgets/group/group.testdata.ts
  packages/perseus/src/widgets/passage/__tests__/passage.test.tsx
  packages/perseus/src/widgets/radio/__tests__/radio.test.ts
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/radio/radio.ff.tsx
  packages/perseus/src/widgets/radio/radio.ts
  packages/perseus/src/widgets/radio/serialize-radio.test.ts
  packages/perseus/src/widgets/radio/util.test.ts
  packages/perseus/src/widgets/radio/util.ts
  packages/perseus/src/widgets/radio/utils/general-utils.test.ts
  packages/perseus/src/widgets/radio/utils/general-utils.ts
Labels: olc-5.0.5f719

#2841 Remove some serialized state APIs
  .changeset/chilly-bees-invite.md
  packages/perseus-core/src/types.ts
  packages/perseus/src/__tests__/renderer.test.tsx
  packages/perseus/src/__tests__/server-item-renderer.test.tsx
  packages/perseus/src/hint-renderer.tsx
  packages/perseus/src/hints-renderer.tsx
  packages/perseus/src/mixins/widget-prop-denylist.ts
  packages/perseus/src/renderer.tsx
  packages/perseus/src/server-item-renderer.tsx
  packages/perseus/src/types.ts
  packages/perseus/src/user-input-manager.test.tsx
  packages/perseus/src/user-input-manager.tsx
  packages/perseus/src/widgets/__testutils__/renderQuestion.tsx
  packages/perseus/src/widgets/categorizer/categorizer.tsx
  packages/perseus/src/widgets/categorizer/serialize-categorizer.test.ts
  packages/perseus/src/widgets/cs-program/cs-program.tsx
  packages/perseus/src/widgets/cs-program/serialize-cs-program.test.ts
  packages/perseus/src/widgets/dropdown/dropdown.tsx
  packages/perseus/src/widgets/dropdown/serialize-dropdown.test.ts
  packages/perseus/src/widgets/expression/expression.tsx
  packages/perseus/src/widgets/expression/serialize-expression.test.ts
  packages/perseus/src/widgets/free-response/serialize-free-response.test.ts
  packages/perseus/src/widgets/grapher/grapher.tsx
  packages/perseus/src/widgets/grapher/serialize-grapher.test.ts
  packages/perseus/src/widgets/group/group.test.tsx
  packages/perseus/src/widgets/group/group.tsx
  packages/perseus/src/widgets/iframe/iframe.tsx
  packages/perseus/src/widgets/iframe/serialize-iframe.test.ts
  packages/perseus/src/widgets/input-number/input-number.tsx
  packages/perseus/src/widgets/input-number/serialize-input-number.test.ts
  packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
  packages/perseus/src/widgets/interactive-graphs/interactive-graph.tsx
  packages/perseus/src/widgets/interactive-graphs/serialize-interactive-graph.test.ts
  packages/perseus/src/widgets/label-image/__tests__/serialize-label-image.test.ts
  packages/perseus/src/widgets/label-image/label-image.tsx
  packages/perseus/src/widgets/matcher/matcher.tsx
  packages/perseus/src/widgets/matcher/serialize-matcher.test.tsx
  packages/perseus/src/widgets/matrix/matrix.tsx
  packages/perseus/src/widgets/matrix/serialize-matrix.test.ts
  packages/perseus/src/widgets/mock-widgets/mock-widget.tsx
  packages/perseus/src/widgets/number-line/number-line.tsx
  packages/perseus/src/widgets/number-line/serialize-number-line.test.ts
  packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
  packages/perseus/src/widgets/numeric-input/serialize-numeric-input.test.ts
  packages/perseus/src/widgets/orderer/orderer.tsx
  packages/perseus/src/widgets/orderer/serialize-orderer.test.ts
  packages/perseus/src/widgets/plotter/plotter.tsx
  packages/perseus/src/widgets/plotter/serialize-plotter.test.ts
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/radio/radio.ff.tsx
  packages/perseus/src/widgets/radio/radio.ts
  packages/perseus/src/widgets/radio/serialize-radio.test.ts
  packages/perseus/src/widgets/sorter/serialize-sorter.test.ts
  packages/perseus/src/widgets/sorter/sorter.tsx
  packages/perseus/src/widgets/table/serialize-table.test.ts
  packages/perseus/src/widgets/table/table.tsx
  testing/render-question-with-cypress.tsx
Labels: olc-5.0.e7698

#2877 Sync dependencies with Frontend
  .changeset/slow-peas-cough.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
  utils/sync-dependencies.ts
Labels: project agnostic, olc-5.0.0b737

#2880 Add a dependency to wonder-blocks-modal
  .changeset/modern-comics-march.md
  packages/perseus/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.0b737

#2875 Revert "[Radio] Fix iOS mobile hover issue when use is dragging the screen left or right"
  .changeset/flat-moles-drop.md
  packages/perseus/src/widgets/radio/choice-indicator.module.css
  packages/perseus/src/widgets/radio/choice.module.css
Labels: project: new radio widget

#2868 fix: update radio editor to normalize choice ids for existing content
  .changeset/fast-lamps-cough.md
  packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
  packages/perseus-editor/src/widgets/radio/editor.tsx
Labels: project: new radio widget, olc-5.0.5f719

#2893 Remove onChange from UniversalWidgetProps
  .changeset/fast-mangos-trade.md
  packages/perseus/src/types.ts
  packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx
  packages/perseus/src/widgets/matcher/matcher.tsx
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
  packages/perseus/src/widgets/radio/radio-component.tsx
  packages/perseus/src/widgets/table/table.tsx
Labels: olc-5.0.0b737

#2883 [Image] | (a11y) | Add `longDescription` to Image widget ("Explore image" button + modal) for mobile
  .changeset/funny-masks-sparkle.md
  packages/perseus/src/widgets/image/__docs__/explore-image-modal.stories.tsx
  packages/perseus/src/widgets/image/__docs__/image-regression.stories.tsx
  packages/perseus/src/widgets/image/components/explore-image-button.tsx
  packages/perseus/src/widgets/image/components/image-description-and-caption.tsx
  packages/perseus/src/widgets/image/image-widget.module.css
Labels: olc-5.0.0b737

#2897 Fix image widget sizing within grouped questions
  .changeset/swift-dancers-join.md
  packages/perseus/src/components/fixed-to-responsive.tsx
  packages/perseus/src/components/image-loader.tsx
  packages/perseus/src/components/svg-image.tsx
  packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
  packages/perseus/src/widgets/image/__snapshots__/image.test.ts.snap
  packages/perseus/src/widgets/image/image.tsx
Labels: olc-5.0.0b737

#2894 In sync-dependencies.ts, error if frontend doesn't provide a peer dep
  .changeset/big-dogs-fix.md
  pnpm-workspace.yaml
  utils/sync-dependencies.ts
Labels: olc-5.0.0b737

#2904 Update dependencies
  .changeset/grumpy-cherries-travel.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.0b737

#2903 [Numeric Input] Fix rendering error in InputWithExamples, changing replaceAll to replace to be old browser compatible
  .changeset/stupid-rockets-float.md
  packages/perseus/src/widgets/numeric-input/input-with-examples.test.tsx
  packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
Labels: olc-5.0.0b737

#2910 docs(changeset): Fixing several issues related to User Input in our Explanation and Number Line Widgets
  .changeset/tiny-rocks-whisper.md
  packages/perseus-editor/src/widgets/number-line-editor.tsx
  packages/perseus/src/widgets/explanation/explanation.tsx
  packages/perseus/src/widgets/number-line/number-line.tsx
Labels: olc-5.0.0b737

#2924 [Image] Add feature flag check for decorative props in Image Widget
  .changeset/swift-wolves-serve.md
  packages/perseus/src/widgets/image/image.tsx
Labels: olc-5.0.2f60c

#2926 [Image] | (CX) | Make image dimensions editable in Image widget editor
  .changeset/new-donkeys-drop.md
  packages/perseus-editor/src/__tests__/editor.test.tsx
  packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx
  packages/perseus-editor/src/widgets/image-editor/components/image-dimensions-input.tsx
  packages/perseus-editor/src/widgets/image-editor/components/image-settings.tsx
  packages/perseus-editor/src/widgets/image-editor/components/image-url-input.tsx
  packages/perseus-editor/src/widgets/image-editor/image-editor.module.css
  packages/perseus-editor/src/widgets/image-editor/image-editor.tsx
  packages/perseus-editor/src/widgets/image-editor/utils.test.ts
  packages/perseus-editor/src/widgets/image-editor/utils.ts
Labels: olc-5.0.2f60c

#2919 [Radio] Add screen reader announcements to help clarify state to the user
  .changeset/nice-actors-brush.md
  packages/perseus/package.json
  packages/perseus/src/strings.ts
  packages/perseus/src/widgets/radio/__docs__/a11y.mdx
  packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: project: new radio widget, olc-5.0.0b737

#2927 [Image] | (CX) | Remove "math in caption" linter error
  .changeset/great-houses-wonder.md
  packages/perseus-linter/src/rules/image-widget.test.ts
  packages/perseus-linter/src/rules/image-widget.ts
Labels: olc-5.0.2f60c

#2934 Require dependencies as a prop for HintRenderer
  .changeset/brave-boxes-rule.md
  packages/perseus/src/__docs__/hints-renderer.stories.tsx
  packages/perseus/src/hint-renderer.tsx
  packages/perseus/src/hints-renderer.tsx
  packages/perseus/src/server-item-renderer.tsx
Labels: olc-5.0.853e0
